language: node_js
node_js:
  - "7.8.0"

addons:
  postgresql: "9.6"

after_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -d travis_ci_test -a -f ./init_scripts/musicio2.sql

after_success: npm run coverage
