language: node_js
node_js:
  - "7.8.0"

services:
  - postgresql

before_script:
  - psql -c 'create database musicio2;' -U postgres
  - psql -U postgres -d musicio2 -a -f ./init_scripts/musicio2.sql

after_success: npm run coverage
